--drop table IF EXISTS users CASCADE;
--drop table IF EXISTS authorities CASCADE;
drop table IF EXISTS product_name CASCADE;
drop table IF EXISTS product_measure CASCADE;
drop table IF EXISTS product CASCADE;
--drop table IF EXISTS recipe CASCADE;
drop table IF EXISTS photo_link CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      varchar(50),
    username        varchar(50)                             not null,
    password        varchar(249)                            not null,
    email           varchar(50),
    phone_number    varchar(12),
    enabled         boolean,
    email_confirmed boolean,
    primary key (username)
);

CREATE TABLE IF NOT EXISTS authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  varchar                                 not null,
    authority varchar(50)                             not null,
    constraint fk_authorities_users foreign key (username) references users (username)
);

CREATE TABLE IF NOT EXISTS product_name
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name varchar                                 not null
);

CREATE TABLE IF NOT EXISTS product_measure
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_measure varchar                                 not null
);

CREATE TABLE IF NOT EXISTS recipe
(
    recipe_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar                                 not null,
    description   varchar                                 not null,
    duration      DOUBLE PRECISION                        not null,
    date_creating TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_login    varchar,
    is_moderated  boolean,
    is_public     boolean,
    constraint recipe_id_fk_user foreign key (user_login) references users (username),
    primary key (recipe_id)
);

CREATE TABLE IF NOT EXISTS product
(
    product_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name     varchar                                 not null,
    product_measure  varchar                                 not null,
    product_quantity DOUBLE PRECISION                        not null,
    rec_id           INTEGER,
    constraint recipe_id_fk_product foreign key (rec_id) references recipe (recipe_id),
    primary key (product_id)
);

CREATE TABLE IF NOT EXISTS photo_link
(
    photo_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipe_id     INTEGER,
    link          varchar                                 not null,
    --constraint recipe_id_fk_product foreign key (recipe_id) references recipe (recipe_id),
    primary key (photo_link_id)
)